// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getDecks() : Promise<Result<Deck[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_decks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDeck(deckId: string) : Promise<Result<Deck, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_deck", { deckId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDeck(input: CreateDeckInput) : Promise<Result<Deck, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_deck", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDeck(deckId: string, input: UpdateDeckInput) : Promise<Result<Deck, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_deck", { deckId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDeck(deckId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_deck", { deckId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCards(deckId: string, filter: CardFilter | null) : Promise<Result<CardSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cards", { deckId, filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCard(cardId: string, deckId: string) : Promise<Result<Card, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_card", { cardId, deckId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateUserNotes(cardId: string, deckId: string, notes: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_user_notes", { cardId, deckId, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDeckFolder(folderPath: string) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_deck_folder", { folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCardsFolder(deckId: string, folderPath: string) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_cards_folder", { deckId, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ZIP からデッキまるごと取り込む（deck.json 必須）(§5.3)。
 */
async importDeckZip(zipPath: string) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_deck_zip", { zipPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ZIP から既存デッキへカードのみ取り込む（deck.json 不要）(§5.3)。
 */
async importCardsZip(deckId: string, zipPath: string) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_cards_zip", { deckId, zipPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ZIP バイト列からデッキまるごと取り込む（Android の content:// URI 対応版）(§5.3, §10.2)。
 * フロントが readFile() でバイト列を読み取り、このコマンドへ渡す。
 */
async importDeckZipBytes(data: number[]) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_deck_zip_bytes", { data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ZIP バイト列から既存デッキへカードのみ取り込む（Android の content:// URI 対応版）(§5.3, §10.2)。
 */
async importCardsZipBytes(deckId: string, data: number[]) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_cards_zip_bytes", { deckId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 全データ（全デッキ＋カード＋学習進捗＋履歴）を zip バイト列でエクスポートする。
 * フロントは受け取ったバイト列を `save()` で選んだ保存先へ `writeFile()` する。
 */
async exportBackup() : Promise<Result<number[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_backup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * バックアップ zip バイト列をマージ復元する（content:// 対応のためバイト列受け）。
 * `deck_ids` を指定すると、そのデッキだけを選択復元する（null = 全件）。
 */
async importBackup(data: number[], deckIds: string[] | null) : Promise<Result<BackupImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_backup", { data, deckIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * セッションキューを構築する (spec §6.1)。
 * daily_new_limit / daily_review_limit はモード横断の合計として適用する。
 */
async getSessionQueue(deckId: string) : Promise<Result<SessionCard[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_queue", { deckId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 回答前に各評価ボタンの次回間隔ラベルを計算する（DBには書き込まない）。
 * spec §6.4 の「今日中 / N日後」表示用。
 */
async previewReview(cardId: string, deckId: string, mode: string) : Promise<Result<IntervalPreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_review", { cardId, deckId, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 回答を採点し FSRS でスケジューリングする (spec §12 submit_review)
 */
async submitReview(cardId: string, deckId: string, mode: string, rating: string) : Promise<Result<SubmitReviewResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_review", { cardId, deckId, mode, rating }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHomeStats() : Promise<Result<HomeStats, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_home_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * デッキ全体の習得度内訳を算出する（デッキ詳細画面の「学習進捗」表示用）。
 * 学習単位は (カード × テストモード)。未学習はレコードが無いユニットなので、
 * カード数から学習済み（learning/review 等）を差し引いて算出する。
 */
async getDeckProgress(deckId: string) : Promise<Result<DeckProgress, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_deck_progress", { deckId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppState() : Promise<Result<AppStateData, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppState(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_state", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async log(logLevel: LogLevel, log: string) : Promise<void> {
    await TAURI_INVOKE("log", { logLevel, log });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * アプリ全体のエラー型 (spec §12 共通型定義)
 */
export type AppError = { Database: string } | { NotFound: string } | { Validation: string } | { Io: string }
export type AppStateData = { theme: string; last_used_deck_id: string | null; window_width: number; window_height: number; window_x: number | null; window_y: number | null; 
/**
 * TTS 読み上げ音量 (0.0〜1.0)。未設定なら 1.0。
 */
tts_volume: number; 
/**
 * リスニング出題を含めるか。未設定なら true。
 * false のとき listening モードを出題キュー・進捗分母から除外する（無音環境用）。
 */
listening_enabled: boolean }
/**
 * バックアップ取り込み結果の集計。
 */
export type BackupImportResult = { decks: number; cards_created: number; cards_updated: number; srs_imported: number; logs_imported: number }
export type Card = { id: string; deck_id: string; hanzi: string; pinyin_accepted: string[]; meaning: string; example_sentences: ExampleSentence[]; synonyms: string[]; antonyms: string[]; tags: string[]; ai_notes: string | null; user_notes: string; audio_path: string | null; created_at: string; updated_at: string }
export type CardFilter = { search_text: string | null; tags: string[] | null; srs_state: string | null }
/**
 * カード一覧用の軽量型（モードごとのSRS状態を含む）
 */
export type CardSummary = { id: string; deck_id: string; hanzi: string; meaning: string; pinyin_accepted: string[]; tags: string[]; 
/**
 * デッキの各テストモードに対する状態 ('new'|'learning'|'review'|'relearning')
 */
srs_states: ModeState[] }
export type CreateDeckInput = { id: string; name: string; description: string | null; language: string; test_modes: string[]; daily_new_limit: number; daily_review_limit: number; 
/**
 * 1日の学習量の目安（None なら無効）。詳細は Deck::daily_study_target を参照。
 */
daily_study_target: number | null; fsrs_target_retention: number; fsrs_max_interval_days: number }
export type DayForecast = { 
/**
 * JST の日付 (YYYY-MM-DD)
 */
date: string; 
/**
 * その日に期日が来る復習の件数（learning/relearning/review、上限未適用の生件数）
 */
reviews: number; 
/**
 * その日に新規導入される見込み枚数（日次新規上限と残数からシミュレート）
 */
new_cards: number; 
/**
 * 延滞（期限切れ）件数。先読みなので今日のバーのみ非ゼロ。
 */
overdue: number }
export type Deck = { id: string; name: string; description: string | null; language: string; test_modes: string[]; daily_new_limit: number; daily_review_limit: number; 
/**
 * 1日の学習量の目安（新規カードの自動調整用）。None なら無効。
 * 有効時は「新規＋復習」がこの枚数を超えないよう新規のみを絞る（復習は絞らない）。
 */
daily_study_target: number | null; fsrs_target_retention: number; fsrs_max_interval_days: number; created_at: string; updated_at: string; 
/**
 * カード総数（一覧表示用に算出）
 */
card_count: number; 
/**
 * 今日の新規予定数（実効上限 = daily_new_limit - 今日導入済み、学習量の目安によるスロットルを反映）
 */
new_today: number; 
/**
 * 今日の復習予定数（state='review' かつ期日到来）
 */
review_today: number; 
/**
 * 学習中カード数（learning/relearning かつ期日到来、同日再出題対象）
 */
learning_today: number; 
/**
 * daily_study_target により今日の新規が絞られている場合 true（UI で「調整中」を示す用）
 */
new_limited_by_study: boolean }
export type DeckDueCount = { deck_id: string; deck_name: string; 
/**
 * 今日の新規予定（実効上限を反映）
 */
new_count: number; 
/**
 * 今日の復習予定（state='review' かつ期日到来、上限適用後）
 */
review_count: number; 
/**
 * 学習中カード（learning/relearning かつ期日到来、同日再出題対象）
 */
learning_count: number; completed_today: number }
/**
 * デッキ全体の習得度内訳（デッキ詳細画面の「学習進捗」表示用）。
 * 学習の単位は (カード × テストモード)。未学習はレコードが無いユニット。
 */
export type DeckProgress = { 
/**
 * 総ユニット数 = カード数 × テストモード数
 */
total_units: number; 
/**
 * 未学習（srs_record が無い、または state='new'）
 */
new_count: number; 
/**
 * 学習中（state が learning / relearning）
 */
learning_count: number; 
/**
 * 習得中（state='review' かつ 復習間隔 < 21日）
 */
young_count: number; 
/**
 * 定着（state='review' かつ 復習間隔 >= 21日）
 */
mature_count: number; 
/**
 * モード別の内訳
 */
modes: ModeProgress[]; 
/**
 * 今日の完了数（review_logs より、JST 論理日付ベース）
 */
completed_today: number }
export type ExampleSentence = { text: string; pinyin?: string; translation?: string }
export type HomeStats = { streak_days: number; today_reviewed: number; deck_due_counts: DeckDueCount[]; seven_day_forecast: DayForecast[] }
export type ImportResult = { created: number; updated: number }
/**
 * 答えフェーズで各評価ボタンに表示する次回間隔プレビュー
 */
export type IntervalPreview = { again: string; hard: string; good: string; easy: string }
export type LogLevel = "ERROR" | "WARN" | "INFO" | "DEBUG" | "VERBOSE"
/**
 * テストモード1つ分の習得度内訳。
 */
export type ModeProgress = { mode: string; new_count: number; learning_count: number; young_count: number; mature_count: number }
export type ModeState = { mode: string; state: string }
export type SessionCard = { card: Card; mode: string; srs_state: string }
export type SrsRecord = { card_id: string; deck_id: string; mode: string; due_date: string; stability: number | null; difficulty: number | null; state: string; reps: number; lapses: number; last_review: string | null; scheduled_days: number; elapsed_days: number }
export type SubmitReviewResult = { updated_srs: SrsRecord; 
/**
 * new_due_date の日付(JST) == 今日(JST) の場合 true
 */
should_requeue: boolean; 
/**
 * 各評価ボタンに表示する次回予定（"今日中" / "N日後"）
 */
interval_preview: IntervalPreview }
export type UpdateDeckInput = { name: string; description: string | null; language: string; test_modes: string[]; daily_new_limit: number; daily_review_limit: number; 
/**
 * 1日の学習量の目安（None なら無効）。詳細は Deck::daily_study_target を参照。
 */
daily_study_target: number | null; fsrs_target_retention: number; fsrs_max_interval_days: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
